---
title: '17、async / await函数'
categories: 日常总结
tags:
 - js
 - es6
collapsable: true
---

### 概念
::: tip
async函数的返回值是一个Promise对象，可以看作多个Promise包装成的一个Promise对象，可以使用then方法添加回调函数，一旦遇到await就会先返回，等到异步操作完成后，在进行下一步的操作。

await函数正常情况下跟的也是一个Promise对象，返回该对象的结果，如果不是Promise对象，就直接返回对应的值，就是内部then命令的语法糖（简写）
:::

#### 用法
```js
async function a(val, ms) {
    await new Promise(resolve => {
        setTimeout(() => {
            resolve(val)
        }, ms)
    }).then(val => console.log(val))
    console.log(2)
    return 3
}
a(1,2000).then(val => console.log(val)) // 两秒钟后输出1  2   3
// async 函数内部返回Promise对象 return 3，await后面跟着Promise，两秒后resolve(1)，正是因为有await关键字，所以需要此异步操作执行完成后才继续往下执行，因此输出处顺序为 1 2 3
```

- 如果将上面方法中的await关键字去掉，那么会立刻输出 2  3 两秒后输出 1

#### async函数返回的Promise对象，必须等到内部的await命令后跟的Promise对象执行完成，才能发生状态变化，除非遇到return语句或者抛出错误，只有async内部的异步函数执行完成，才会执行async函数的then方法回调
```js
// 内部执行完才执行getTitle函数的then方法
async function getTitle(url) {
    let response = await fetch(url);
    let html = await response.text();
    return html.match(/<title>([\s\S]+)<\/title>/i)[1];
}
getTitle('https://tc39.github.io/ecma262/').then(console.log)
```

#### await后面如果跟的是thenable对象，那么会当作Promise对象处理，例如通常await后面跟的ajax函数
```js
async function thenAble(url) {
    let a = null
    await axios.get(url).then(res => {
        if(res.status === 200) {
            a = 1
        }
    })
    let b = 1
    await axios.get(url).then(res => {
        if(res.status === 200) {
            b += a
        }
    })
    let c = 3
    console.log(a, b, c)    // 1  2  3
}
```

#### 任何一个await语句后面的 Promise 对象变为reject状态，那么整个async函数都会中断执行
```js
async function f() {
    await Promise.reject('出错了');
    await Promise.resolve('hello world'); // 不会执行
}
```


#### 错误处理
- 将认为会出错的await放在try里面
```js
async function f() {
    try {
        await Promise.reject('出错了');
    } catch(e) {
    }
    return await Promise.resolve('hello world');
}
f().then(v => console.log(v))   //  hello world
```

- await后面跟catch方法
```js
async function f() {
    await Promise.reject('出错了').catch(erro => {
        console.log(erro)
    })
    return await Promise.resolve('hello world');
}
f().then(v => console.log(v))   //  出错了  hello world
```

- 如果await后的Promise抛出错误，等同于async函数返回的Promise对象被reject
```js
async function a() {
    await new Promise((resolve,reject) => {
        reject('出错了')
    })
}
a().then().catch(erro => {
    console.log(erro)   // 出错了
})
```

#### 使用注意点
1、await后跟的Promise对象很可能会被reject，建议将await用try catch处理，或者await后跟catch方法捕获错误
```js
async function myFunction() {
    try {
        await something();
    } catch (err) {
        console.log(err);
    }
}

// 另一种写法
async function myFunction() {
    await something()
    .catch(err => {
        console.log(err);
    });
}
```

2、await后面跟的异步操作，如果不存在继发关系（没有先后关联，没有先后依赖），尽量同时触发
```js
// 这种需要等待getFoo执行完在执行getBar，耗时
let foo = await getFoo();
let bar = await getBar();

// 写法一，利用Promise.all()
let [foo, bar] = Promise.all([getFoo(), getBar()])

// 写法二
let fooPromise = getFoo();
let bar = getBar();
await foo = fooPromise;
await bar = barPromise;
```

3、await只能用在async函数中

4、async函数可以保留运行堆栈
```js
// a函数运行，内部执行异步方法b函数，当b函数还未执行完成的时候，a方法可能已经执行完成，此时b或c方法报错的话，错误堆栈不包含a方法
const a = () => {
    b().then(() => c());
};

// 改成 async/await 形式，a方法将被暂停，直到b方法执行完成a方法才继续执行，一旦b或c方法报错，错误堆栈将包含a方法
const a = async () => {
    await b();
    c();
}
```

#### 读取一组url，按顺序输出结果
```js
// 虽然可以顺序处理，但是是继发执行，不能同时执行，需要等待上个结果完成后才能继续下一步，希望是并发执行
async function getUrResponse(urlArr) {
    for(const url of urlArr) {
        const res = await fetch(url);
        const resText = await res.test()
        console.log(resText);
    }
}

// 修改后 虽然map函数的参数是async函数，但也是并发执行，因为只有async函数内部才是继发执行，外部没影响
async function getUrResponse(urlArr) {
    const promiseTextArr = urlArr.map(async url => {
        const res = await fetch(url);
        const resText = await res.test();
        return resText;
    })
    for(const promiseText of promiseTextArr) {
        console.log(promiseText);
    }
}
```
